document.getElementById('shell').innerHTML = Aero.shell();
const input=Aero.$('#fileInput'), drop=Aero.$('#dropzone'), launch=Aero.$('#launchBtn');
let file=null, jobId=null, poll=null;
const stages=['Video ingestion','Quality filtering','Keyframe selection','Dynamic masking','Structure from Motion','Dense reconstruction','Meshing & texturing','Georeferencing','Analysis','Deliverable export'];
Aero.$('#stageList').innerHTML=stages.map((s,i)=>`<div class="stage" data-stage="${i+1}"><span class="stage-num">${i+1}</span><span>${s}</span></div>`).join('');
Aero.$('#browseBtn').onclick=()=>input.click(); input.onchange=()=>choose(input.files[0]);
['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('dragover')}));
['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('dragover')}));
drop.addEventListener('drop',e=>choose(e.dataTransfer.files[0]));
Aero.$('#fps').oninput=e=>Aero.$('#fpsLabel').textContent=`${Number(e.target.value).toFixed(1)} FPS`;
function choose(chosen){if(!chosen)return;file=chosen;Aero.$('#fileMeta').classList.remove('hidden');Aero.$('#fileName').textContent=chosen.name;Aero.$('#fileSize').textContent=`${(chosen.size/1048576).toFixed(1)} MB`;Aero.$('#preview').src=URL.createObjectURL(chosen);Aero.$('#dropTitle').textContent='Flight source ready';Aero.$('#dropHelp').textContent='Review the preview, then launch the pipeline.';launch.disabled=false;Aero.$('#launchHint').textContent='The upload stays on this reconstruction server.'}
launch.onclick=async()=>{if(!file)return;launch.disabled=true;Aero.$('#progressCard').classList.remove('hidden');setProgress(4,'Uploading source video');try{const form=new FormData();form.append('file',file);const uploaded=await Aero.api('/upload',{method:'POST',body:form});jobId=uploaded.job_id;setProgress(8,'Starting reconstruction');await Aero.api(`/reconstruct/${jobId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target_fps:Number(Aero.$('#fps').value),mapper_backend:Aero.$('#mapper').value,processing_profile:Aero.$('#profile').value,cpu_threads:Number(Aero.$('#threads').value),skip_dynamic_masking:!Aero.$('#masking').checked,skip_depth_estimation:false})});localStorage.setItem('aerosynth:lastJob',jobId);poll=setInterval(check,1400);check()}catch(e){fail(e.message)}};
async function check(){try{const j=await Aero.api(`/status/${jobId}`);setProgress(j.progress||0,j.message||j.stage);Aero.$$('.stage').forEach((el,i)=>{el.classList.toggle('done',i<(j.stage_index||0));el.classList.toggle('active',i===(j.stage_index||0)-1)});if(j.status==='completed'){clearInterval(poll);setProgress(100,'Reconstruction complete');Aero.toast('Reconstruction complete');setTimeout(()=>location.href='/outputs',900)}else if(j.status==='failed'){clearInterval(poll);fail(j.message)}}catch(e){clearInterval(poll);fail(e.message)}}
function setProgress(p,t){Aero.$('#progressBar').style.width=`${p}%`;Aero.$('#progressPct').textContent=`${Math.round(p)}%`;Aero.$('#progressTitle').textContent=t}
function fail(message){setProgress(0,'Reconstruction stopped');launch.disabled=false;Aero.toast(message,true);Aero.$('#launchHint').innerHTML=`<span class="bad">${message}</span>`}
