document.getElementById('shell').innerHTML = Aero.shell();
const canvas = document.getElementById('studioCanvas');
const ctx = canvas.getContext('2d');
let points = [], yaw = -.55, pitch = -.32, zoom = 1, spin = true, dragging = false, lastX = 0, lastY = 0;

function resize() { const box=canvas.getBoundingClientRect(), d=Math.min(devicePixelRatio,2); canvas.width=box.width*d; canvas.height=box.height*d; ctx.setTransform(d,0,0,d,0,0); }
function drawGrid(w,h) { ctx.strokeStyle='rgba(145,205,235,.095)'; ctx.lineWidth=1; const step=46; for(let x=w%step;x<w;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()} for(let y=h%step;y<h;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()} }
function render(){ const {width:w,height:h}=canvas.getBoundingClientRect(); ctx.clearRect(0,0,w,h); drawGrid(w,h); if(spin&&!dragging&&points.length) yaw+=.0014; if(points.length){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch), scale=Math.min(w,h)*.38*zoom; const projected=points.map(p=>{const x=p[0]*cy-p[2]*sy,z=p[0]*sy+p[2]*cy,y=p[1]*cp-z*sp,d=3.2+(p[1]*sp+z*cp);return [w/2+x*scale/d,h/2-y*scale/d,d,p[3],p[4],p[5]]}).sort((a,b)=>b[2]-a[2]); projected.forEach(p=>{const alpha=Math.max(.25,Math.min(.95,1.15-p[2]*.12));ctx.fillStyle=`rgba(${p[3]},${p[4]},${p[5]},${alpha})`;ctx.fillRect(p[0],p[1],1.8,1.8)}) } requestAnimationFrame(render); }
function normalize(raw){if(!raw.length)return[];const stride=Math.max(1,Math.floor(raw.length/50000)),sample=raw.filter((_,i)=>i%stride===0);const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];sample.forEach(p=>{for(let i=0;i<3;i++){min[i]=Math.min(min[i],p[i]);max[i]=Math.max(max[i],p[i])}});const center=min.map((v,i)=>(v+max[i])/2),span=Math.max(...max.map((v,i)=>v-min[i]),.001);return sample.map(p=>[(p[0]-center[0])/span,(p[1]-center[1])/span,(p[2]-center[2])/span,p[3]||120,p[4]||210,p[5]||240])}
async function loadJobs(){try{const r=await Aero.api('/jobs'), completed=r.jobs.filter(j=>j.status==='completed');studioJob.innerHTML=completed.length?completed.map(j=>`<option value="${j.job_id}">${j.filename||j.job_id.slice(0,8)}</option>`).join(''):'<option value="">No completed reconstructions</option>';if(completed.length)loadJob(studioJob.value);else projectMessage.textContent='Complete a reconstruction to inspect it here.'}catch(e){projectMessage.textContent=e.message;Aero.toast(e.message,true)}}
async function loadJob(id){if(!id)return;viewerState.textContent='Loading geometry';try{const [payload,metrics]=await Promise.all([Aero.api(`/points/${id}`),Aero.api(`/measurements/${id}`)]);points=normalize(payload.points||[]);viewerEmpty.classList.toggle('hidden',points.length>0);pointCount.textContent=`${(metrics.dense_points||payload.points?.length||0).toLocaleString()} points`;viewerState.textContent=points.length?'Geometry active':'No point preview';projectMessage.textContent=`Loaded ${id.slice(0,8)} · verified project output`;statSparse.textContent=(metrics.sparse_points||0).toLocaleString();statDense.textContent=(metrics.dense_points||0).toLocaleString();statVertices.textContent=(metrics.mesh_vertices||0).toLocaleString();statTriangles.textContent=(metrics.mesh_triangles||0).toLocaleString();statReprojection.textContent=metrics.reprojection_error_px!=null?`${metrics.reprojection_error_px} px`:'—';statGsd.textContent=typeof metrics.gsd_cm_px==='number'?`${metrics.gsd_cm_px.toFixed(2)} cm/px`:'Unavailable';statCrs.textContent=metrics.crs||'Local metric'}catch(e){points=[];viewerEmpty.classList.remove('hidden');viewerState.textContent='Output unavailable';projectMessage.textContent=e.message}}
canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw+=(e.clientX-lastX)*.008;pitch=Math.max(-1.2,Math.min(1.2,pitch+(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.45,Math.min(3,zoom*(e.deltaY>0?.91:1.1)))},{passive:false});
toggleSpin.onclick=()=>{spin=!spin;toggleSpin.textContent=spin?'Pause rotation':'Resume rotation'};resetView.onclick=()=>{yaw=-.55;pitch=-.32;zoom=1};studioJob.onchange=()=>loadJob(studioJob.value);addEventListener('resize',resize);resize();render();loadJobs();
